name: Build & Test
on:
  push:
    branches: ["production", "development"]
  pull_request:
    branches: ["production", "development"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Gradle Cache
        uses: actions/cache@v3.0.8
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew buildmock
      - name: Test with Gradle
        run: ./gradlew testmock
